[project]
name = "fastapi-project-structure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.7",
    "uvicorn>=0.40.0",
]
